name: Pull Request

on:
  pull_request:
    branches:
      - develop

permissions:
  actions: read
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/workflows/templates/install

      - name: Validate PR commits
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Lint check
        run: pnpm exec nx affected -t=lint --base=develop --head=HEAD --parallel --configuration=ci
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/workflows/templates/install

      - name: Test
        run: pnpm exec nx run-many --target=test --all --parallel --configuration=ci

      - name: Publish test report
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
        with:
          coverageCommand: pnpm run coverage-merge
          coverageLocations: |
            ${{ github.workspace }}/coverage/lcov.info:lcov
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/workflows/templates/install

      - name: Build
        run: pnpm exec nx run-many --target=build --all --parallel --configuration=ci
  build_storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/workflows/templates/install

      - name: Build
        run: pnpm build-storybook --configuration=ci
